### ISSUE TITLE
[FEAT] - Database for Social Links

### ISSUE THREAD

**Issue by naomi-lgbt** [nhcarrigan/4c-active-member-bot#3]
### What feature would you like to see?

We should add a feature that allows members to add their twitter and github links to our database - then, when a member list is requests, we can include these social links.

### Additional information

Technical implementations:

- Use MongoDB, with the `mongoose` package. This can be the user schema:

```ts
{
  "userId": String,
  "twitter": String,
  "github": String,
}
```

- Create a `/socials` command which allows people to submit their social link to the bot.
  - The first `option` should be a string option, with pre-defined choices for the socials we support (we can type this to match the schema keys, too)
  - The second `option` should take the link to their social.

**Comment by abuna1985** [comment]
I would like to work on this issue

**Comment by abuna1985** [comment]
I would like to work on this feature. Can I be assigned to this issue?

**Comment by naomi-lgbt** [comment]
Thank you for your interest in contributing~!

We are currently evaluating whether the community still needs/uses this project - thanks for your patience while we determine the future path for this repository.

**Comment by naomi-lgbt** [comment]
Closing in prep for archival
