### ISSUE TITLE
[FEAT] - Generate list of participants in a voice chat

### ISSUE THREAD

**Issue by naomi-lgbt** [nhcarrigan/4c-active-member-bot#4]
### What feature would you like to see?

We should add a command that allows staff to generate a list of members currently engaged in a voice chat.

Because this list should also return their socials, this is blocked until #2 is resolved.

### Additional information

Technical details:

- Slash command should check that the user calling the command has staff permissions (`PermissionsFlagBits.ManageMessages` should be good enough, here)
- Slash command should take a single `channel` option - We can use `.addChannelTypes()` on the builder to restrict to `ChannelTypes.GuildVoice` and `ChannelTypes.GuildStageVoice`.
- Command logic should fetch list of members, iterate and query DB for each, then build array of JSON object results.

**Comment by Vyvy-vi** [comment]
I'd like to work on this

**Comment by naomi-lgbt** [comment]
Thank you for your interest in contributing~!

We are currently evaluating whether the community still needs/uses this project - thanks for your patience while we determine the future path for this repository.

**Comment by naomi-lgbt** [comment]
Closing in prep for archival
